"""
Golden-master end-to-end test: DNL x Muddle Through (milestone M1).

Asserts the production FcfEngine reconstructs the audited workbook
(dnl_muddle_through_valuation_v6) to within tolerance, line-for-line and at the
headline. The oracle fixture golden/dnl_mt_v6.json is regenerated by
golden/_recalc.py (LibreOffice headless); this test reads the committed JSON and
needs no spreadsheet tooling.

Tolerances (engine implementation plan, section 3):
    per-share      : +/- 0.05 absolute AND +/- 0.5%
    terminal share : +/- 0.5pp
    line items     : +/- 0.5% (relative), +/- 0.05 absolute floor
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from vcc_valuations.dcf.fcf_engine import FcfEngine, FcfDcfResult
from tests.dcf.golden.dnl_mt_inputs import dnl_muddle_through_inputs

GOLDEN = json.loads((Path(__file__).parent / "golden" / "dnl_mt_v6.json").read_text())
PER_SHARE_ORACLE = 3.484
EV_ORACLE = 7736.61


@pytest.fixture(scope="module")
def result() -> FcfDcfResult:
    return FcfEngine().run(dnl_muddle_through_inputs())


def _close(got: float, want: float, rel: float = 0.005, abs_floor: float = 0.05) -> bool:
    return abs(got - want) <= max(abs_floor, abs(want) * rel)


@pytest.mark.parametrize(
    "attr",
    [
        "revenue", "ebit_margin", "ebit", "applied_tax_rate",
        "tax", "nopat", "da", "capex", "fcff",
        "mid_times", "pv_fcff",
    ],
)
def test_line_vectors_match_workbook(result: FcfDcfResult, attr: str) -> None:
    got = getattr(result, attr)
    want = GOLDEN["vectors"][attr]
    assert len(got) == len(want), f"{attr}: length {len(got)} != {len(want)}"
    for period, (g, w) in enumerate(zip(got, want)):
        assert _close(g, w), f"{attr}[{period}] = {g:.4f}, workbook {w:.4f}"


def test_discount_factors_match(result: FcfDcfResult) -> None:
    for period, (g, w) in enumerate(zip(result.discount_factors, GOLDEN["vectors"]["discount_factor"])):
        assert _close(g, w, rel=0.001, abs_floor=1e-4), f"DF[{period}] {g} vs {w}"


def test_wacc_single_and_matches(result: FcfDcfResult) -> None:
    assert _close(result.wacc, GOLDEN["scalars"]["wacc"], rel=0.001, abs_floor=1e-4)
    assert result.wacc == pytest.approx(0.0827551, abs=1e-6)


def test_terminal_block_matches(result: FcfDcfResult) -> None:
    s = GOLDEN["scalars"]
    assert _close(result.terminal_growth, s["terminal_growth"], abs_floor=1e-6)
    assert _close(result.terminal_fcff, s["terminal_fcff"])
    assert _close(result.terminal_value, s["terminal_value"])
    assert _close(result.terminal_end_time, s["terminal_end_time"], abs_floor=1e-6)
    assert _close(result.pv_terminal, s["pv_terminal"])


def test_enterprise_value_matches(result: FcfDcfResult) -> None:
    assert _close(result.pv_explicit, GOLDEN["scalars"]["pv_explicit"])
    assert _close(result.enterprise_value, GOLDEN["scalars"]["enterprise_value"])
    assert _close(result.enterprise_value, EV_ORACLE, abs_floor=1.0)


def test_equity_bridge_matches(result: FcfDcfResult) -> None:
    s = GOLDEN["scalars"]
    assert _close(result.net_debt_at_valuation, s["net_debt_at_valuation"])
    assert _close(result.equity_bridge_adjustments_net, s["equity_bridge_adjustments_net"])
    # workbook stores the lease line as a negative deduction; engine holds the magnitude
    assert _close(result.lease_liabilities, abs(s["lease_liabilities"]), abs_floor=1e-6)
    assert _close(result.equity_value, s["equity_value"])
    assert result.shares_outstanding == pytest.approx(s["shares_outstanding"])


def test_headline_per_share(result: FcfDcfResult) -> None:
    # acceptance number: 3.48 (lease-reanchored v6), NOT the pre-lease 3.59
    assert abs(result.value_per_share_reported - PER_SHARE_ORACLE) <= 0.05
    assert _close(result.value_per_share_reported, GOLDEN["scalars"]["value_per_share"])


def test_terminal_share_within_half_pp(result: FcfDcfResult) -> None:
    assert abs(result.terminal_share_of_ev - GOLDEN["scalars"]["terminal_share_of_ev"]) <= 0.005


def test_terminal_share_fires_nonblocking_warning(result: FcfDcfResult) -> None:
    assert result.terminal_share_of_ev > 0.70
    assert any("sensitivity pass" in w for w in result.warnings)


def test_market_discount_sign(result: FcfDcfResult) -> None:
    assert result.discount_to_market is not None
    assert -0.05 < result.discount_to_market < 0.0
